### ISSUE TITLE
Dummy Data

### ISSUE THREAD

**Issue by howdysuraj** [rsudharsan/WorkflowApproval#1]
Kindly provide the dummy data for running the application. The API's are built well and good but they do not return anything yet.
You have tested in your localhost where even the mongodb instance is in your local machine. I guess providing a copy of your nosql db should work well and good.

or we need some different procedure to run the application, please update the readme with instructions. @rsudharsan

**Comment by rsudharsan** [comment]
I have uploaded dump in resources : db name: workflow - db name can be modified in application.properties if you are importing with diff name

https://github.com/rsudharsan/WorkflowApproval/blob/master/src/main/resources/static/schema/workflow.zip
